java_test(
    name = "messenger-test",
    srcs = [
        "MessengerTest.java"
    ],
    test_class = "com.bmuschko.messenger.MessengerTest",
    deps = [
        "//src/main/java/com/bmuschko/messenger:messenger-lib",
         "@maven//:junit_junit",
    ],
)