java_library(
    name = "messenger-lib",
    srcs = ["Messenger.java"],
    visibility = [
        "//src/main/java/com/bmuschko:__pkg__",
        "//src/test/java/com/bmuschko/messenger:__pkg__"
    ],
    deps = [
        "@maven//:org_apache_commons_commons_lang3",
    ],
)